apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DRONE_REPO_OWNER}-${DRONE_REPO_NAME}
spec:
  selector:
    matchLabels:
      run: ${DRONE_REPO_OWNER}-${DRONE_REPO_NAME}
  replicas: 2
  template:
    metadata:
      labels:
        run: ${DRONE_REPO_OWNER}-${DRONE_REPO_NAME}
    spec:
      containers:
      - name: ${DRONE_REPO_OWNER}-${DRONE_REPO_NAME}
        image: ${ECR_REPOSITORY_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ${DRONE_REPO_OWNER}-${DRONE_REPO_NAME}
  labels:
    run: ${DRONE_REPO_OWNER}-${DRONE_REPO_NAME}
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: ${DRONE_REPO_OWNER}-${DRONE_REPO_NAME}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${DRONE_REPO_OWNER}-${DRONE_REPO_NAME}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ${DRONE_REPO_OWNER}-${DRONE_REPO_NAME}.hvt.zone
    http:
      paths:
      - path: "/"
        backend:
          serviceName: ${DRONE_REPO_OWNER}-${DRONE_REPO_NAME}
          servicePort: 80
